language: php

php:
  - 5.6
  - 7.0
  
services:
  - mysql
  
install:
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-dist --dev --no-interaction
  
before_script:
  - sudo mysql -e 'CREATE DATABASE gabs;use gabs;set names utf8;source sql/db.sql;'
  - sudo mysql -e "use mysql;update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';grant all privileges on *.* to 'root'@'localhost' identified by 'root' with grant option;FLUSH PRIVILEGES;"
  - mkdir -p build/logs
  - ls -al
  
script:
  - phpunit --coverage-clover build/logs/clover.xml
  
after_script:  
  - vendor/bin/php-coveralls -v